stages:
  run_pipeline:
    cmd: kedro run
    deps:
      - proyectomachineml/src
      - proyectomachineml/conf
      - proyectomachineml/data/01_raw
      - proyectomachineml/data/02_intermediate
      - proyectomachineml/data/03_primary
      - proyectomachineml/data/05_model_input
    outs:
      - proyectomachineml/data/06_models
      - proyectomachineml/data/07_model_output
